//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetTakip_UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class MailKaydet : global::System.Configuration.ApplicationSettingsBase {
        
        private static MailKaydet defaultInstance = ((MailKaydet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MailKaydet())));
        
        public static MailKaydet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KaydetsinMi {
            get {
                return ((bool)(this["KaydetsinMi"]));
            }
            set {
                this["KaydetsinMi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonMail {
            get {
                return ((string)(this["SonMail"]));
            }
            set {
                this["SonMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SonSifre {
            get {
                return ((string)(this["SonSifre"]));
            }
            set {
                this["SonSifre"] = value;
            }
        }
    }
}
